name: Lab1

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y dotnet-sdk-7.0 python3 python3-pip fsharp
          pip3 install pylint
          dotnet tool install --global fantomas-tool --version "4.*"

  build:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Build task7
        run: |
          dotnet build src/task7/inf --configuration Release
          dotnet build src/task7/rec --configuration Release
          dotnet build src/task7/tail_rec --configuration Release
          dotnet build src/task7/module  --configuration Release
          dotnet build src/task7/map --configuration Release
      - name: Build task26
        run: |
          dotnet build src/task26/inf  --configuration Release
          dotnet build src/task26/rec  --configuration Release
          dotnet build src/task26/tail_rec  --configuration Release
          dotnet build src/task26/module  --configuration Release
          dotnet build src/task26/map --configuration Release
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: src/bin/Release

  lint:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Format F# code with Fantomas
        run: fantomas src --recurse
      - name: Upload formatted files
        uses: actions/upload-artifact@v3
        with:
          name: formatted-src
          path: src

  test:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Run Tests
        run: |
          dotnet test src --no-restore
      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: ./TestResults

  run_python:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Run Python Lint and Scripts
        run: |
          pylint src/task7.py src/task26.py
          python3 src/task7.py
          python3 src/task26.py