name: Lab1

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y dotnet-sdk-7.0 python3 python3-pip fsharp
          pip3 install pylint
          dotnet tool install --global fantomas-tool --version "4.*"
          dotnet tool install --global FSharpLint.Tool --version "0.14.*"
          echo "::add-path::${HOME}/.dotnet/tools"

  build:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Build
        run: |
          dotnet restore src
          dotnet build src --no-restore --configuration Release
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: src/bin/Release

  lint:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Run F# Lint
        run: |
          fsharplint lint src/task7/task7.fs
          fsharplint lint src/task26/task26.fs

  format:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Format F# code with Fantomas
        run: fantomas src --recurse
      - name: Upload formatted files
        uses: actions/upload-artifact@v3
        with:
          name: formatted-src
          path: src
        if: github.event_name == 'pull_request'

  test:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Run Tests
        run: |
          dotnet test src --no-restore
      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: ./TestResults

  run_python:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Run Python Lint and Scripts
        run: |
          pylint src/task7.py src/task26.py
          python3 src/task7.py
          python3 src/task26.py